# Generated by Django 5.2.1 on 2025-11-27 15:51

import astrology.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AstrologySession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.TextField()),
                ('gender', models.CharField(max_length=32)),
                ('birth_date', models.TextField(blank=True, null=True)),
                ('birth_time', models.TextField(blank=True, null=True)),
                ('birth_place', models.TextField(blank=True, null=True)),
                ('preferences', models.TextField(blank=True, null=True)),
                ('openai_result', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=16)),
                ('consent_to_store', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(default=astrology.models.default_expires_at)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
