# Generated by Django 5.2.1 on 2025-11-29 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologysession',
            name='gender',
            field=models.TextField(),
        ),
    ]
