# Generated by Django 5.2.1 on 2025-11-29 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reading',
            name='reading_type',
            field=models.CharField(choices=[('palm_analysis', 'Palm Analysis'), ('numerology', 'Numerology'), ('astrology_reading', 'Astrology Reading')], default='palm_analysis', help_text='Type of reading: palm_analysis, numerology, or astrology_reading', max_length=32),
        ),
    ]
