# Generated by Django 5.2.9 on 2025-12-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0003_add_palm_reference_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='palm_reference',
            field=models.ForeignKey(blank=True, help_text='Reference to the palm reading that this reading is based on (for numerology/astrology integration)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_readings', to='readings.reading'),
        ),
    ]
